<?php
header("Content-Type:text/html;charset=utf-8");
//配置用例相关的常量
define("DOWNLOAD_DIR","./download/");
define("ROOT_DIR",$_SERVER['DOCUMENT_ROOT']);
define("SUITE1","测试用例集1");
define("SUITE2","测试用例集2");
define("REQUIREMENT","测试需求");
define("TC_NAME","用例名称");
define("PRIORITY","优先级");
define("EXECUTION_TYPE","执行方式");
define("KEYWORD","关键字");
define("SUMMARY","摘要");
define("PRECONDITION","前提条件");
define("ACTION","操作步骤");
define("EXPECTED_RESULTS","预期结果");
define("ESTIMATED_TIME","预估用时");
define("AUTHOR","编写人");
//配置需求相关的常量
define("SPECIFICATION_ID","软件需求集编号");
define("SPECIFICATION","软件需求集");
define("REQUIREMENT_I","软件需求编号");
define("REQUIREMENT_D","软件需求简述");
define("REQUIREMENT_P","软件需求优先级");
define("REQUIREMENT_F","软件需求来源");
define("USER_SCENE","用户场景说明");
define("REQUIREMENT_S","适用范围");
define("REMARK","备注");
define("TR_ID","测试需求编号");
define("TR_NAME","测试需求名称");
define("TR_D","测试需求描述");
define("TR_P","测试需求优先级");
define("TR_T","测试类型");
define("TR_S","用例规模");
define("TR_M","用例设计方法");
?>